#!/usr/bin/python
# -*- coding: UTF-8 -*-

# @date: 2020-06-12 
# @name: constant
# @author：shimengqi

# 响应成功，状态码200
CODE_SUCCESS = 0
MSG_SUCCESS = '成功'

# 参数错误100 - 199
CODE_PARAM_INVALID = 101
MSG_PARAM_INVALID = "参数无效"

CODE_PARAM_IS_BLANK = 102
MSG_PARAM_IS_BLANK = "参数为空"

CODE_PARAM_TYPE_BIND_ERROR = 103
MSG_PARAM_TYPE_BIND_ERROR = "参数类型错误"

CODE_PARAM_NOT_COMPLETE = 104
MSG_PARAM_NOT_COMPLETE = "关键参数缺失"


# 用户错误200 - 299 token失效或权限认证错误，状态码401
CODE_USER_NOT_LOGGED_IN = 201
MSG_USER_NOT_LOGGED_IN = "用户未登录"

CODE_USER_LOGIN_ERROR = 202
MSG_USER_LOGIN_ERROR = "账号不存在或密码错误"

CODE_USER_ACCOUNT_FORBIDDEN = 203
MSG_USER_ACCOUNT_FORBIDDEN = "账号已被禁用"

CODE_USER_NOT_EXIST = 204
MSG_USER_NOT_EXIST = "用户不存在"

CODE_USER_HAS_EXISTED = 205
MSG_USER_HAS_EXISTED = "用户已存在"

CODE_USER_HAS_NO_PERMISSION=206
MSG_USER_HAS_NO_PERMISSION="用户无权限"

# 未发现接口
CODE_NOT_FOUND_ERROR = '401'
MSG_NOT_FOUND_ERROR = '服务器没有此接口'

# token失效或权限认证错误，状态码401
CODE_AUTH_ERROR = '000001'
MSG_AUTH_ERROR = 'token认证失败, 请重新登录'
# 业务上的错误
CODE_BUSSINESS_ERROR = '000002'
MSG_BUSSINESS_ERROR = ''
# 服务器内部错误，状态码500
CODE_SERVER_ERROR = '000003'
MSG_SERVER_ERROR = '网络操作失败，请稍后重试'
# 未发现接口
CODE_NOT_FOUND_ERROR = '000004'
MSG_NOT_FOUND_ERROR = '服务器没有此接口'
# 未知错误
CODE_UNKNOWN_ERROR = '000005'
MSG_UNKNOWN_ERROR = '未知错误'
# 拒绝访问
CODE_REJECT_ERROR = '000006'
MSG_REJECT_ERROR = '拒绝访问'
# 拒绝访问
CODE_METHOD_ERROR = '000007'
MSG_METHOD_ERROR = '请求方法错误'
# 缺少参数
CODE_PARAMETER_ERROR = '000008'
MSG_PARAMETER_ERROR = '缺少参数'
