# Generated by Django 3.0.6 on 2020-06-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200624_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='abc', max_length=30, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(default=None, max_length=30, verbose_name='名字'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_active',
            field=models.CharField(default='1', max_length=30, verbose_name='是否激活'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_superuser',
            field=models.CharField(default='0', max_length=10, verbose_name='是否超级用户'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_login',
            field=models.DateField(auto_now=True, verbose_name='最近登录'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(default=None, max_length=30, verbose_name='姓氏'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='update_time',
            field=models.DateField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
