# Generated by Django 3.0.6 on 2020-06-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200628_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(blank=True, max_length=30, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_login',
            field=models.DateField(blank=True, verbose_name='最近登录'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='姓氏'),
        ),
    ]
